# Generated by Django 6.0.2 on 2026-02-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveBigIntegerField(),
        ),
    ]
