# Generated by Django 6.0.2 on 2026-02-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bus_available_seats_alter_bus_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='available_seats',
        ),
    ]
